config/routes.rb
Rails.application.routes.draw do
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    article = Article.new(article_params)
    article.save
    redirect_to articles_path
  end

  def edit
  end

  def update
    @article.update(article_params)
    redirect_to articles_path
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end

  def set_article
    @article = Article.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<div class="wrapper">
  <h1>Edit an article to Wikinimous</h1>
</div>

<div class="container">
  <%= form_for(@article) do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :content %>
      <%= f.text_field :content, class: 'form-control' %>
    </div>

    <%= f.submit class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/articles/index.html.erb
<%= link_to 'Add an article', new_article_path %>
<div class="wrapper">
  <h1>Wikinimous</h1>
</div>

<div class="container">
  <div class="row">
      <% @articles.each do |article| %>
        <div class="col-xs-12">
          <h2><%= link_to article.title, article_path(article[:id]) %></h2>
        </div>
        <div class="col-xs-12">
          <%= link_to 'Edit', edit_article_path(article[:id]) %>
          <%= link_to 'Delete Article', article_path(article[:id]), method: :delete, data: { confirm: "Are you sure?" } %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/articles/new.html.erb
<div class="wrapper">
  <h1>Add an article to Wikinimous</h1>
</div>

<div class="container">
  <%= form_for(@article) do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :content %>
      <%= f.text_field :content, class: 'form-control' %>
    </div>

    <%= f.submit class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/articles/show.html.erb
<div class="wrapper">
  <h1><%= link_to 'Wikinimous', articles_path %></h1>
</div>

<div class="container">
  <%= @article.title %>
  <%= @article.content %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <partials navbar>
    <%= yield %>
  </body>
</html>